--Change unit_price from varchar to float
SELECT
  REPLACE(UNIT_PRICE, ',', '.')::FLOAT AS UNIT_PRICE,
FROM
  "CASE_STUDY_1"."PUBLIC"."BRIGHT_COFFEE_SALES";

--Total sales by time of day
SELECT 
  TRANSACTION_DATE,
  TRANSACTION_TIME,
  STORE_LOCATION,
  PRODUCT_CATEGORY,
  PRODUCT_TYPE,
  PRODUCT_DETAIL,
  TRANSACTION_QTY,
  UNIT_PRICE,
  TRANSACTION_QTY * REPLACE(UNIT_PRICE, ',', '.')::FLOAT AS TOTAL_REVENUE,

  CASE 
    WHEN DATE_PART('hour', TRANSACTION_TIME) BETWEEN 5 AND 11 THEN 'Morning'
    WHEN DATE_PART('hour', TRANSACTION_TIME) BETWEEN 12 AND 17 THEN 'Afternoon'
    ELSE 'Evening'
  END AS TIME_OF_DAY

FROM "CASE_STUDY_1"."PUBLIC"."BRIGHT_COFFEE_SALES";

--Sales by product type
SELECT 
  PRODUCT_TYPE,
  SUM(TRANSACTION_QTY) AS TOTAL_UNITS_SOLD,
  SUM(TRANSACTION_QTY * REPLACE(UNIT_PRICE, ',', '.')::FLOAT) AS TOTAL_REVENUE
FROM "CASE_STUDY_1"."PUBLIC"."BRIGHT_COFFEE_SALES"
GROUP BY PRODUCT_TYPE
ORDER BY TOTAL_REVENUE DESC;

--Top 10 best selling products by quantity
SELECT 
  PRODUCT_DETAIL,
  SUM(TRANSACTION_QTY) AS TOTAL_UNITS_SOLD
FROM "CASE_STUDY_1"."PUBLIC"."BRIGHT_COFFEE_SALES"
GROUP BY PRODUCT_DETAIL
ORDER BY TOTAL_UNITS_SOLD DESC
LIMIT 10;

--Revenue by time of day
SELECT 
  CASE 
    WHEN DATE_PART('hour', TRANSACTION_TIME) BETWEEN 5 AND 11 THEN 'Morning'
    WHEN DATE_PART('hour', TRANSACTION_TIME) BETWEEN 12 AND 17 THEN 'Afternoon'
    ELSE 'Evening'
  END AS TIME_OF_DAY,
  SUM(TRANSACTION_QTY * REPLACE(UNIT_PRICE, ',', '.')::FLOAT) AS TOTAL_REVENUE
FROM "CASE_STUDY_1"."PUBLIC"."BRIGHT_COFFEE_SALES"
GROUP BY TIME_OF_DAY
ORDER BY TOTAL_REVENUE DESC;

--Sales by store location
SELECT 
  STORE_LOCATION,
  SUM(TRANSACTION_QTY) AS TOTAL_UNITS_SOLD,
  SUM(TRANSACTION_QTY * REPLACE(UNIT_PRICE, ',', '.')::FLOAT) AS TOTAL_REVENUE
FROM "CASE_STUDY_1"."PUBLIC"."BRIGHT_COFFEE_SALES"
GROUP BY STORE_LOCATION
ORDER BY TOTAL_REVENUE DESC;

--Daily sales trend
SELECT 
  TRANSACTION_DATE,
  SUM(TRANSACTION_QTY * REPLACE(UNIT_PRICE, ',', '.')::FLOAT) AS DAILY_REVENUE
FROM "CASE_STUDY_1"."PUBLIC"."BRIGHT_COFFEE_SALES"
GROUP BY TRANSACTION_DATE
ORDER BY TRANSACTION_DATE;



